[package]
name = "cliente"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
